Repository Open-Agriculture/AgIsoStack-rs, pull requests merged in 2023-08, with the labels that each got.

#7 Fix broken CI pipeline on main
  .github/workflows/build.yml
Labels: bug

#6 Add NAME
  src/lib.rs
  src/network_management/mod.rs
  src/network_management/name.rs
Labels: enhancement

#11 Add control function and common PGNs
  Cargo.toml
  src/network_management/common_parameter_group_numbers.rs
  src/network_management/control_function.rs
  src/network_management/mod.rs
Labels: enhancement

#4 Add initial Frame, Address, and PGN types
  src/driver/address.rs
  src/driver/can_id.rs
  src/driver/frame.rs
  src/driver/mod.rs
  src/driver/pgn.rs
  src/lib.rs
Labels: enhancement

#18 Replaces 'cobertura-action' with 'codecov' for coverage reports
  .github/workflows/ci.yml
Labels: ci/cd

#19 Change tarpaulin coverage to use llvm engine
  .github/workflows/ci.yml
Labels: ci/cd
